In [12]:
import numpy as np
import matplotlib.pyplot as plt
import array
from itertools import product
import numpy as np
import sys
from src.loaders import load_data, load_labels
from src.classify import MCM_Classifier
from src.plot import plot_confusion_matrix, plot_label_prob_diff


import small_mcm_tools as tools
import ebo_best_basis
import numpy as np


In [13]:
c_binary_data = tools.generate_class_dataset("c")

In [18]:
np.array([i.flatten() for i in c_binary_data])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 1., 0., 0.],
       [0., 0., 0., 1., 0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [0.

In [7]:
a = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])
b = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])/2
m = np.array([a,b])

In [8]:
print(m)

[[[1.  2.  3. ]
  [4.  5.  6. ]
  [0.  0.  0. ]]

 [[0.5 1.  1.5]
  [2.  2.5 3. ]
  [0.  0.  0. ]]]


In [11]:
stacked_array = np.concatenate(m)

# Reshape the result to get a 2D array with lists at each position
# entry_wise = stacked_array.reshape(-1, stacked_array.shape[-1])
# entry_wise
print(stacked_array)

[[1.  2.  3. ]
 [4.  5.  6. ]
 [0.  0.  0. ]
 [0.5 1.  1.5]
 [2.  2.5 3. ]
 [0.  0.  0. ]]


In [5]:
original_shape = (3, 3, 2)
stacked_array_back = entry_wise.reshape(original_shape)

# The resulting matrix 'm'
m_back = np.dstack(stacked_array_back)

NameError: name 'entry_wise' is not defined

In [ ]:
m_back

array([[[1. , 4. , 0. ],
        [0.5, 2. , 0. ]],

       [[2. , 5. , 0. ],
        [1. , 2.5, 0. ]],

       [[3. , 6. , 0. ],
        [1.5, 3. , 0. ]]])