In [5]:
import numpy as np

In [43]:
a = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])
b = np.array([[1, 2, 3], [4, 5, 6], [0, 0, 0]])/2
m = np.array([a,b])

In [44]:
print(m)

[[[1.  2.  3. ]
  [4.  5.  6. ]
  [0.  0.  0. ]]

 [[0.5 1.  1.5]
  [2.  2.5 3. ]
  [0.  0.  0. ]]]


In [60]:
stacked_array = np.dstack(m)

# Reshape the result to get a 2D array with lists at each position
entry_wise = stacked_array.reshape(-1, stacked_array.shape[-1])
entry_wise

array([[1. , 0.5],
       [2. , 1. ],
       [3. , 1.5],
       [4. , 2. ],
       [5. , 2.5],
       [6. , 3. ],
       [0. , 0. ],
       [0. , 0. ],
       [0. , 0. ]])

In [84]:
original_shape = (3, 3, 2)
stacked_array_back = entry_wise.reshape(original_shape)

# The resulting matrix 'm'
m_back = np.dstack(stacked_array_back)

In [85]:
m_back

array([[[1. , 4. , 0. ],
        [0.5, 2. , 0. ]],

       [[2. , 5. , 0. ],
        [1. , 2.5, 0. ]],

       [[3. , 6. , 0. ],
        [1.5, 3. , 0. ]]])