### Simple accuracy table. All 5423 sample MCM on train data

In [1]:
import numpy as np
import os
import json
import sys
import matplotlib.pyplot as plt
import skimage

sys.path.append("../")
import src.plot as myplot
import seaborn as sns

import sklearn

In [2]:
import importlib
import src.plot as myplot
importlib.reload(myplot)

<module 'src.plot' from '/Users/paulhosek/PycharmProjects/mcm/MCM_classifier/Classifier_1/0_classifier/paper_plots/../src/plot.py'>

In [3]:

import importlib
import src.paper_utils as utils
importlib.reload(utils)

<module 'src.paper_utils' from '/Users/paulhosek/PycharmProjects/mcm/MCM_classifier/Classifier_1/0_classifier/paper_plots/../src/paper_utils.py'>

In [13]:
sample_sizes = [5423]
counts_samplesizes, mcms_samplesizes = utils.load_counts_mcm(sample_sizes, letter="", path_format="../data/Output/mcm/sample_sizes")
atest_mcms, atest_probs = utils.get_complete_testprobs(mcms_samplesizes,counts_samplesizes,sample_sizes,n_runs=2,smooth=True)

In [14]:
test_mcms = atest_mcms[:,0,0]
test_probs = atest_probs[:,0,0]


(10, 10, 121, 892)

In [36]:
per_image_prob = np.product(test_probs,axis=2,where=test_probs!=-1)

In [37]:
per_image_prob.shape # mcm, digit, image

(10, 10, 892)

In [77]:
# have probability per mcm for seeing every other digit and every image

# want 1. test accuracy table
# -> for how many images is the highest probability the one for the right mcm
# for every digit (ax=1), check the 

# maxs[8,:]

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 6, 8, 8, 4, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0, 8, 5, 8, 9,
       7, 8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 8, 8, 8, 8,
       8, 3, 8, 8, 5, 8, 8, 3, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 4, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 5, 3,
       8, 8, 8, 3, 2, 8, 8, 8, 8, 8, 8, 3, 8, 8, 2, 8, 2, 8, 8, 8, 8, 2,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 8, 8, 3, 8, 6, 8, 8, 8, 0, 8, 8, 8, 8, 8, 8, 7, 8, 8, 8, 8,
       8, 8, 8, 3, 8, 8, 3, 8, 8, 8, 8, 2, 8, 8, 1, 8, 2, 1, 8, 8, 8, 8,
       1, 5, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9,
       8, 8, 8, 2, 8, 8, 8, 8, 8, 8, 8, 8, 8, 5, 3, 8, 8, 7, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 0,
       8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 0, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 9, 8, 8, 5, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8,

In [92]:
# digitwise accuracy
max_decision_unit = np.argmax(per_image_prob,axis=0) # out of the 10 mcm seeing the same digit, which one was the most probable
digit_accu = [1-np.count_nonzero(max_decision_unit[k,:] - k)/892 for k in range(10)]
digit_accu
# np.mean(digit_accu)

[0.9730941704035875,
 0.9775784753363229,
 0.9495515695067265,
 0.929372197309417,
 0.9226457399103138,
 0.9204035874439462,
 0.945067264573991,
 0.9047085201793722,
 0.8878923766816144,
 0.8957399103139013]

In [88]:
np.argmax(max_decision_unit,axis=0)

array([9, 9, 9, 9, 9, 9, 8, 8, 8, 7, 9, 7, 9, 9, 9, 8, 4, 9, 8, 9, 9, 9,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 9, 9, 9, 8,
       9, 9, 9, 9, 9, 8, 9, 9, 7, 9, 9, 9, 9, 9, 9, 9, 9, 7, 4, 9, 4, 4,
       9, 9, 9, 7, 9, 9, 9, 4, 9, 4, 9, 9, 9, 9, 4, 9, 9, 9, 7, 8, 9, 9,
       4, 9, 9, 9, 9, 9, 8, 9, 9, 9, 4, 9, 7, 9, 9, 9, 9, 9, 9, 8, 9, 9,
       3, 9, 9, 9, 7, 8, 0, 5, 9, 9, 9, 9, 9, 8, 9, 9, 9, 9, 9, 9, 8, 9,
       9, 9, 7, 9, 9, 9, 4, 9, 9, 9, 4, 4, 4, 9, 9, 9, 9, 8, 8, 8, 9, 9,
       7, 9, 9, 9, 7, 9, 9, 9, 7, 9, 9, 8, 9, 8, 9, 9, 9, 9, 9, 9, 9, 7,
       9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 8, 9, 9, 7, 9, 0, 9, 7, 8, 5, 9, 9,
       4, 9, 4, 9, 8, 9, 9, 9, 7, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 5, 8,
       9, 9, 9, 9, 9, 9, 9, 4, 9, 5, 8, 4, 9, 4, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 4, 9, 8, 9, 9, 9, 9, 9, 9, 8, 9, 9, 9, 8, 9, 9, 9, 9, 9, 9, 9,
       9, 9, 9, 9, 9, 4, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9,
       9, 8, 7, 9, 9, 8, 9, 4, 9, 9, 5, 9, 9, 9, 9,

In [82]:
mcm0_p = per_image_prob[0,:,:]
mcm0_p.shape #mcm0 sees the other digits
np.argmax(mcm0_p,axis=0) # out of the 10 digits that are on index i, what was the most probable under mcm 0? Useless comparison.
#e.g., is the 5 image at this index more probale than the 0 index image?
# NOTE: Maybe this is useful to see which images are confusing images but would need to look accross different mcms

array([0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0,
       0, 6, 0, 0, 0, 6, 0, 0, 0, 0, 6, 0, 0, 0, 0, 6, 0, 0, 7, 0, 0, 0,
       0, 0, 9, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 6, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 6, 0, 0, 0, 9, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0,
       6, 0, 0, 5, 0, 6, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3,
       6, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 6, 0, 0, 0, 0, 3, 0, 0, 0, 0, 9, 0, 0, 0, 0, 7, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 5, 0, 5, 6, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,

In [65]:
tes = np.array([[[10, 11, 12], # digit 0
                [2, 1, 1]], # digit 1
                # mcm 1
                [[0, 1, 2], # digit 0
                [1, 14, 15]]]) # digit 1
print(tes.shape)
np.argmax(tes,axis=1)

(2, 2, 3)


array([[0, 0, 0],
       [1, 1, 1]])